// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_graphqlEndpoint": process.env.GRAPHQL_URL,
    "aws_appsync_apiKey": process.env.AUTH_KEY,
};

export default awsmobile;